#-*- coding: utf-8 -*- 
from database import db_session, Demount, Floor, Wall

def check_db():
    check = db_session.query(Wall.id).distinct().all()
    if check:
        pass
    else:
        import sqlite3
        conn = sqlite3.connect('works.db')
        
        c = conn.cursor()
        
        """ DEMOUNT """
        c.execute('''INSERT INTO DEMOUNT VALUES (1, "Демонтаж конструкций из лгк", 30, "м2")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (2, "Демонтаж бетонных перегородок", 200, "м2")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (3, "Очистка от старой краски", 17.5, "м2")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (4, "Демонтаж вагонки", 20, "м2")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (5, "демонтаж цементнопесчанной стяжки до 100мм.", 100, "м2")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (6, "Демонтаж металлоконструкций", 3000, "т")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (7, "Устройство дверных проёмов в кирпичной стене(1/2 кирпича)", 300, "шт")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (8, "Устройство дверных проёмов в бетонной стене(до 200 мм.)", 600, "шт")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (9, "Очистка от старой краски", 17, "м2")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (10, "Cнятие старых обоев", 13, "м2")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (11, "Сбивка старой штукатурки", 17, "м2")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (12, "Демонтаж керамической плитки", 30, "м2")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (13, "Разборка полов из ленолеума(ковролина)", 20, "м2")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (14, "Разборка паркетного пола", 25, "м2")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (15, "Демонтаж дверного блока", 70, "шт")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (16, "Демонтаж оконного блока", 70, "шт")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (17, "Демонтаж ванны", 120, "шт")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (18, "Демонтаж труб", 8, "пм")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (19, "Демонтаж умывальника", 30, "шт")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (20, "Демонтаж унитаза", 30, "шт")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (21, "Разборка потолка армстронг", 17, "м2")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (22, "Демонтаж электропроводки", 8, "пм")''')
        c.execute('''INSERT INTO DEMOUNT VALUES (23, "Демонтаж розеток и выключателей", 16, "шт")''')
        
        """ FLOOR """
        c.execute('''INSERT INTO FLOOR VALUES (1, "Цементнопесчанная стяжка до 50мм.", 50, "м2")''')
        c.execute('''INSERT INTO FLOOR VALUES (2, "Цементнопесчанная стяжка до 100мм.", 70, "м2")''')
        c.execute('''INSERT INTO FLOOR VALUES (3, "Самовыравнивающая стяжка", 40, "м2")''')
        c.execute('''INSERT INTO FLOOR VALUES (4, "Керамзитобетонная стяжка", 60, "м2")''')
        c.execute('''INSERT INTO FLOOR VALUES (5, "Укладка бетона", 160, "м2")''')
        c.execute('''INSERT INTO FLOOR VALUES (6, "Армирование стяжки", 20, "м2")''')
        c.execute('''INSERT INTO FLOOR VALUES (7, "Гидроизоляция", 20, "м2")''')
        c.execute('''INSERT INTO FLOOR VALUES (8, "Наливные полы", 100, "м2")''')
        c.execute('''INSERT INTO FLOOR VALUES (9, "Теплые полы", 50, "м2")''')
        c.execute('''INSERT INTO FLOOR VALUES (10, "Ламинат", 50, "м2")''')
        c.execute('''INSERT INTO FLOOR VALUES (11, "Устройство фанеры или OSB на пол (в 1 слой)", 20, "м2")''')
        c.execute('''INSERT INTO FLOOR VALUES (12, "Линолиум", 30, "м2")''')
        c.execute('''INSERT INTO FLOOR VALUES (13, "Ковролин", 35, "м2")''')
        c.execute('''INSERT INTO FLOOR VALUES (14, "Половая доска", 17, "м2")''')
        c.execute('''INSERT INTO FLOOR VALUES (15, "Паркет-доска", 70, "м2")''')
        c.execute('''INSERT INTO FLOOR VALUES (16, "Паркет", 90, "м2")''')
        c.execute('''INSERT INTO FLOOR VALUES (17, "Художественный паркет", 115, "м2")''')
        c.execute('''INSERT INTO FLOOR VALUES (18, "Шлифовка, лакировка пола", 35, "м2")''')
        c.execute('''INSERT INTO FLOOR VALUES (19, "Монтаж плинтусов пластиковых", 16, "пм")''')
        c.execute('''INSERT INTO FLOOR VALUES (20, "Монтаж плинтусов деревянных", 30, "пм")''')
        
        """ WALL """
        c.execute('''INSERT INTO WALL VALUES (1, "Устройство перегородок кирпичных 120мм", 60, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (2, "Устройство перегородок из пеноблоков", 60, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (3, "Звукоизоляция стен минеральной ватой", 12, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (4, "Устройство полистирольных плит на стены в один слой", 20, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (5, "Устройство полистирольных плит на стены в один слой в уровень", 25, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (6, "Монтаж сетки штукатурной", 15, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (7, "Монтаж уголка металического", 12, "пм")''')
        c.execute('''INSERT INTO WALL VALUES (8, "Устройство штукатурки маячной до 30 мм", 55, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (9, "Устройство перегородок из ЛГК", 80, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (10, "Устройство фальшстен из ЛГК", 50, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (11, "Монтаж ЛГК конструкций (2-слойная перегородка)", 80, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (12, "Монтаж ЛГК конструкций (короб)", 60, "пм")''')
        c.execute('''INSERT INTO WALL VALUES (13, "Устройство колон из ЛГК", 85, "пм")''')
        c.execute('''INSERT INTO WALL VALUES (14, "Заделка швов ЛГК конструкций", 10, "пм")''')
        c.execute('''INSERT INTO WALL VALUES (15, "Монтаж металического уголка, металической ленты", 12, "пм")''')
        c.execute('''INSERT INTO WALL VALUES (16, "Поклейка малярной сетки на стены", 12, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (17, "Штукатурка стен", 55, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (18, "Грунтовка поверхности 1 слой", 4, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (19, "Беспесчанка стен под обои или декоративную штукатурку", 35, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (20, "Беспесчанка откосов до 300мм, под обои", 120, "пм")''')
        c.execute('''INSERT INTO WALL VALUES (21, "Беспесчанка стен под покраску", 45, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (22, "Беспесчанка откосов до 300мм, под покраску", 120, "пм")''')
        c.execute('''INSERT INTO WALL VALUES (23, "Поклейка стекловолокна на стены", 20, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (24, "Поклейка стекловолокна на откосы до 300мм", 20, "пм")''')
        c.execute('''INSERT INTO WALL VALUES (25, "Поклейка обоев под покраску на стены", 32, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (26, "Поклейка обоев под покраску на откосы до 300мм", 32, "пм")''')
        c.execute('''INSERT INTO WALL VALUES (27, "Поклейка обоев без бодбора рисунка на стены", 40, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (28, "Поклейка обоев без подбора рисунка на откосы до 300мм", 40, "пм")''')
        c.execute('''INSERT INTO WALL VALUES (29, "Поклейка обоев с подбором рисунка на стены", 45, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (30, "Поклейка обоев с подбором рисунка на откосы до 300мм", 45, "пм")''')
        c.execute('''INSERT INTO WALL VALUES (31, "Покраска стен в/є краской", 20, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (32, "Покраска многокомпонентная", 40, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (33, "Покраска откосов до 300мм, валиком 2 раза", 35, "пм")''')
        c.execute('''INSERT INTO WALL VALUES (34, "Устройство декоративной штукатурки на стенах", 50, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (35, "Устройство декоративной штукатурки на откосы до 300мм", 50, "пм")''')
        c.execute('''INSERT INTO WALL VALUES (36, "Устройство венецианской штукатурки, короед", 90, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (37, "Монтаж пластиковой вагонки на стены", 50, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (38, "Монтаж деревянной вагонки на стены", 75, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (39, "Вагонка мдф", 40, "м2")''')
        c.execute('''INSERT INTO WALL VALUES (40, "Сайдинг", 70, "м2")''')
        
        """ DOORWAY """
        c.execute('''INSERT INTO DOORWAY VALUES (1, "Устройство арок ГКЛ", 120, "пм")''')
        c.execute('''INSERT INTO DOORWAY VALUES (2, "Устройство откосов ГКЛ, окон и дверей (монтаж, выготовка, покраска)", 120, "пм")''')
        c.execute('''INSERT INTO DOORWAY VALUES (3, "Устройство полистирольных плит на откосы до 300мм, окон, дверей", 15, "пм")''')
        c.execute('''INSERT INTO DOORWAY VALUES (4, "Устройство маячной штукатурки откосов до 300мм, окон, дверей", 120, "пм")''')
        c.execute('''INSERT INTO DOORWAY VALUES (5, "Монтаж подоконников", 60, "пм")''')
        c.execute('''INSERT INTO DOORWAY VALUES (6, "Монтаж обналичников и расширителей", 15, "пм")''')
        c.execute('''INSERT INTO DOORWAY VALUES (7, "Монтаж деревянных дверных блоков до 2 кв.м.", 250, "шт")''')
        c.execute('''INSERT INTO DOORWAY VALUES (8, "Врезка замков и фурнитуры", 100, "шт")''')
        c.execute('''INSERT INTO DOORWAY VALUES (9, "Установка окон", 200, "шт")''')
        
        """ CEILING """
        c.execute('''INSERT INTO CEILING VALUES (1, "Грунтовка поверхности 1 слой", 5, "м2")''')
        c.execute('''INSERT INTO CEILING VALUES (2, "Штукатурка потолка", 100, "м2")''')
        c.execute('''INSERT INTO CEILING VALUES (3, "Устройство ГКЛ конструкций (1 уровень)", 80, "м2")''')
        c.execute('''INSERT INTO CEILING VALUES (4, "Устройство прямых понижений потолков ГКЛ", 65, "пм")''')
        c.execute('''INSERT INTO CEILING VALUES (5, "Устройство радиусных (кривых) понижений потолков ГКЛ", 80, "пм")''')
        c.execute('''INSERT INTO CEILING VALUES (6, "Монтаж ГКЛ конструкций (короб)", 65, "пм")''')
        c.execute('''INSERT INTO CEILING VALUES (7, "Монтаж натяжных потолков", 90, "м2")''')
        c.execute('''INSERT INTO CEILING VALUES (8, "Устройство потолков 'Армстронг'", 45, "м2")''')
        c.execute('''INSERT INTO CEILING VALUES (9, "Поклейка сетки малярной на потолок", 17, "м2")''')
        c.execute('''INSERT INTO CEILING VALUES (10, "Беспесчанка потолков под обои", 35, "м2")''')
        c.execute('''INSERT INTO CEILING VALUES (11, "Беспесчанка потолков под покраску", 55, "м2")''')
        c.execute('''INSERT INTO CEILING VALUES (12, "Поклейка стекловолокна на потолок", 25, "м2")''')
        c.execute('''INSERT INTO CEILING VALUES (13, "Поклейка стекловолокна на понижение потолков", 25, "пм")''')
        c.execute('''INSERT INTO CEILING VALUES (14, "Поклейка обоев на потолок под покраску, без подбора рисунка", 40, "м2")''')
        c.execute('''INSERT INTO CEILING VALUES (15, "Оклейка обоев шелк,нить,ткань", 50, "м2")''')
        c.execute('''INSERT INTO CEILING VALUES (16, "Покраска потолка", 35, "м2")''')
        c.execute('''INSERT INTO CEILING VALUES (17, "Поклейка багета декоративного до 50 мм", 26, "пм")''')
        c.execute('''INSERT INTO CEILING VALUES (18, "Шпаклевка и покраска декоративного багета до 50 мм", 10, "пм")''')
        c.execute('''INSERT INTO CEILING VALUES (19, "Багеты", 16, "пм")''')
        c.execute('''INSERT INTO CEILING VALUES (20, "Обшивка потолка деревянной вагонкой", 75, "м2")''')
        c.execute('''INSERT INTO CEILING VALUES (21, "Обшивка потолка пластиковой вагонкой", 50, "м2")''')
        
        """ TILE """
        c.execute('''INSERT INTO TILE VALUES (1, "Облицовка пола керамической плиткой", 100, "м2")''')
        c.execute('''INSERT INTO TILE VALUES (2, "Облицовка стен керамической плиткой", 100, "м2")''')
        c.execute('''INSERT INTO TILE VALUES (3, "Облицовка стен керамической плиткой размерами 100х100 мм.", 150, "м2")''')
        c.execute('''INSERT INTO TILE VALUES (4, "Устройство керамического фриза до 100 мм.", 45, "пм")''')
        c.execute('''INSERT INTO TILE VALUES (5, "Облицовка полов мрамором или гранитом", 170, "м2")''')
        c.execute('''INSERT INTO TILE VALUES (6, "Облицовка полов художественной керамической плиткой", 140, "м2")''')
        c.execute('''INSERT INTO TILE VALUES (7, "Облицовка стен мозаикой", 160, "м2")''')
        c.execute('''INSERT INTO TILE VALUES (8, "Облицовка стен декоративной плиткой под 'кирпич' или камень'", 90, "м2")''')
        c.execute('''INSERT INTO TILE VALUES (9, "Облицовка поверхности песчанником", 100, "м2")''')
        c.execute('''INSERT INTO TILE VALUES (10, "Монтаж керамических плинтусов", 35, "пм")''')
        c.execute('''INSERT INTO TILE VALUES (11, "Прирезка керамической плитки прямо", 15, "пм")''')
        c.execute('''INSERT INTO TILE VALUES (12, "Прирезка керамической плитки радиусом / криволинейно", 30, "пм")''')
        c.execute('''INSERT INTO TILE VALUES (13, "Затирка швов плитки", 5, "м2")''')
        c.execute('''INSERT INTO TILE VALUES (14, "Затирка швов плитки под 'кирпич' или 'камень'", 22, "м2")''')
        c.execute('''INSERT INTO TILE VALUES (15, "Прирезка камня", 30, "пм")''')
        c.execute('''INSERT INTO TILE VALUES (16, "Монтаж плиточного декоративного уголка", 25, "пм")''')
        
        """ ELECTRIC """
        c.execute('''INSERT INTO ELECTRIC VALUES (1, "Монтаж эл.точек по кирпичу", 40, "шт")''')
        c.execute('''INSERT INTO ELECTRIC VALUES (2, "Монтаж эл.точек по бетону", 50, "шт")''')
        c.execute('''INSERT INTO ELECTRIC VALUES (3, "Укладка эл.кабеля", 8, "пм")''')
        c.execute('''INSERT INTO ELECTRIC VALUES (4, "Укладка гофры", 4, "пм")''')
        c.execute('''INSERT INTO ELECTRIC VALUES (5, "Укладка металлорукава", 5, "пм")''')
        c.execute('''INSERT INTO ELECTRIC VALUES (6, "Укладка кабель-канала", 4, "пм")''')
        c.execute('''INSERT INTO ELECTRIC VALUES (7, "Монтаж эл.щита", 400, "шт")''')
        c.execute('''INSERT INTO ELECTRIC VALUES (8, "Заземление, громоотвод", 500, "шт")''')
        c.execute('''INSERT INTO ELECTRIC VALUES (9, "Подключение к силовой электросети", 140, "шт")''')
        c.execute('''INSERT INTO ELECTRIC VALUES (10, "Набор электрощита (монтаж автоматов)", 30, "шт")''')
        c.execute('''INSERT INTO ELECTRIC VALUES (11, "Монтаж распределительных коробок и подрозетников", 15, "шт")''')
        c.execute('''INSERT INTO ELECTRIC VALUES (12, "Монтаж, розеток и выключателей", 25, "шт")''')
        c.execute('''INSERT INTO ELECTRIC VALUES (13, "Монтаж точечных светильников", 30, "шт")''')
        c.execute('''INSERT INTO ELECTRIC VALUES (14, "Монтаж светильников, бра", 60, "шт")''')
        c.execute('''INSERT INTO ELECTRIC VALUES (15, "Монтаж люминисцентных светильников", 60, "шт")''')
        c.execute('''INSERT INTO ELECTRIC VALUES (16, "Монтаж люстры", 150, "шт")''')
        c.execute('''INSERT INTO ELECTRIC VALUES (17, "Монтаж и подключение входного звонка", 60, "шт")''')
        c.execute('''INSERT INTO ELECTRIC VALUES (18, "Проектирование схемы силовой электропроводки с учетом нагрузок", 400, "шт")''')
        
        """ SANITARY """
        c.execute('''INSERT INTO SANITARY VALUES (1, "Укладка труб канализации", 25, "пм")''')
        c.execute('''INSERT INTO SANITARY VALUES (2, "Штробление под трубы", 35, "пм")''')
        c.execute('''INSERT INTO SANITARY VALUES (3, "Устройство выводов водоснабжения и отопления", 200, "точка")''')
        c.execute('''INSERT INTO SANITARY VALUES (4, "Устройство выводов (кухня)", 200, "компл")''')
        c.execute('''INSERT INTO SANITARY VALUES (5, "Устройство выводов (стиральная, посудомоечная машина)", 200, "компл")''')
        c.execute('''INSERT INTO SANITARY VALUES (6, "Прокладка ПВХ трубы 50", 25, "пм")''')
        c.execute('''INSERT INTO SANITARY VALUES (7, "Прокладка ПВХ трубы 100", 35, "пм")''')
        c.execute('''INSERT INTO SANITARY VALUES (8, "Термоизоляция трубопровода", 5, "пм")''')
        c.execute('''INSERT INTO SANITARY VALUES (9, "Монтаж счетчиков воды с обратным клапаном", 160, "компл")''')
        c.execute('''INSERT INTO SANITARY VALUES (10, "Монтаж водозапорной арматуры", 40, "шт")''')
        c.execute('''INSERT INTO SANITARY VALUES (11, "Монтаж фильтра грубой очистки", 40, "шт")''')
        c.execute('''INSERT INTO SANITARY VALUES (12, "Монтаж фильтра тонкой очистки", 70, "шт")''')
        c.execute('''INSERT INTO SANITARY VALUES (13, "Монтаж люка ревизии", 50, "шт")''')
        c.execute('''INSERT INTO SANITARY VALUES (14, "Монтаж вентиляционной решетки", 40, "шт")''')
        c.execute('''INSERT INTO SANITARY VALUES (15, "Комплектация отопительных радиаторов", 80, "компл")''')
        c.execute('''INSERT INTO SANITARY VALUES (16, "Монтаж отопительных радиаторов", 560, "шт")''')
        c.execute('''INSERT INTO SANITARY VALUES (17, "Монтаж сантехнических аксессуаров", 40, "шт")''')
        c.execute('''INSERT INTO SANITARY VALUES (18, "Монтаж умывальника", 250, "шт")''')
        c.execute('''INSERT INTO SANITARY VALUES (19, "Монтаж смесителя", 60, "шт")''')
        c.execute('''INSERT INTO SANITARY VALUES (20, "Монтаж сифона", 30, "шт")''')
        c.execute('''INSERT INTO SANITARY VALUES (21, "Монтаж полотенцесушителя", 480, "шт")''')
        c.execute('''INSERT INTO SANITARY VALUES (22, "Монтаж биде, унитаза на пол", 400, "компл")''')
        c.execute('''INSERT INTO SANITARY VALUES (23, "Монтаж консольных биде, унитаза на раму (навесные)", 800, "компл")''')
        c.execute('''INSERT INTO SANITARY VALUES (24, "Монтаж ванной", 640, "шт")''')
        c.execute('''INSERT INTO SANITARY VALUES (25, "Монтаж ванной", 800, "шт")''')
        c.execute('''INSERT INTO SANITARY VALUES (26, "Монтаж душевой кабины", 400, "шт")''')
        c.execute('''INSERT INTO SANITARY VALUES (27, "Монтаж электробойлера", 250, "шт")''')
        
        """ OTHER """
        c.execute('''INSERT INTO OTHER VALUES (1, "Фасовка строительного мусора в мешки", 85, "м3")''')
        c.execute('''INSERT INTO OTHER VALUES (2, "Спуск и загрузка строительного мусора на машину (лифт)", 350, "машина")''')
        c.execute('''INSERT INTO OTHER VALUES (3, "Вывоз строительного мусора", 500, "машина")''')
        c.execute('''INSERT INTO OTHER VALUES (4, "Вынос строительного мусора к мусоросборнику на улицу", 60, "м3")''')
        c.execute('''INSERT INTO OTHER VALUES (5, "Доставка строительных материалов", 250, "машина")''')
        c.execute('''INSERT INTO OTHER VALUES (6, "Разгрузка и подъем строительных материалов (лифт)", 200, "машина")''')
        c.execute('''INSERT INTO OTHER VALUES (7, "Рабочий проект", 80, "м2")''')
        
        conn.commit()
check_db()